import React from "react";
import { Link } from "react-router-dom";
import Lavender from "../../Images/footer_lavender.png";
import "../../Styles/animate.css";

const Footer = () => {
  return (
    <footer className="footer">
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
      <img
        src={Lavender}
        width={80}
        height={80}
        alt=""
        className="footer-image"
      />
    </footer>
  );
};

export default Footer;
